# http://www.appveyor.com/docs/appveyor-yml
environment:
  nodejs_version: '12'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run test

# blacklist
except:
  - gh-pages

cache:
  - node_modules -> package.json

version: "{build}"
build: off
deploy: off
matrix:
  fast_finish: true
